function tombol() {
    const judul = document.getElementById('judul');
    judul.innerHTML = 'CURRICULUM VITAE';
  
    const cv = document.getElementById('cv');
    cv.innerHTML = '<header> <img src="20220506_132139.jpg" alt="foto saya" width="150" height="250"> <h1>Fadhilah Fauza Hamda</h1><p>Kontak Saya</p> <nav> <ul class="breadcrumb"> <li> <a href="https://instagram.com/fdlhfzhd">Instagram</a> </li> <li> <a href="mailto:fadhilah.120140153@student.itera.ac.id">Email</a> </li> <li> <a href="https://github.com/fadhilahfauza">Github</a> </li> <li> <a href="https://wa.me/+6281273078691">WhatsApp</a> </li> </ul> </nav></header> <main> <section> <h2>Tentang Saya</h2> <p class="desk"> Seorang Mahasiswa di Institut Teknologi Sumatera sejak tahun 2020 </p> </section> </main> <figcaption><b>Just Watch This! Ini Tugas DRPL Saya!</b></figcaption> <section> <iframe width="560" height="315" src="https://www.youtube.com/embed/e3dvCVlwdVE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>  <br> <div class="form"> <h2>Hubungi Saya</h2<form method="get"> Nama: <input type="text" name="nama" id="nama" placeholder="Masukkan Nama Anda"/> <p>Sudah nonton film saya?</p> <input type="radio" name="pil" id="sudah" value="sudah" /> <label for="sudah">Sudah</label> &emsp;<input type="radio" name="pil" id="belum" value="Belum" /><label for="belum">belum</label><p>Fasilitas Video Saya</p><input type="checkbox" name="play" id="play" value="play" /><label for="play">Bisa di play </label>&emsp;<input type="checkbox" name="pause" id="pause" value="Pause" /><label for="pause">Bisa di pause </label><br /><input type="checkbox"name="fullscreen"id="fullscreen"value="Fullscreen"/><label for="fullscreen">Bisa di fullscreen </label><br /><input type="checkbox" name="mute" id="mute" value="Mute" /><label for="mute">Bisa di mute </label><br /><input type="checkbox"name="download"id="download"value="Download"/><label for="download">Bisa di download </label><br /><br /><input type="submit" value="kirim" /></form><br />> </center><br>    </div> </section> <h2>Pengalaman</h2> <table border="1"> <thead> <tr> <th rowspan="2">No</th> <th rowspan="2">Organisasi/Kepanitiaan</th> <th rowspan="2">Posisi</th> <th colspan="2">Tahun</th> </tr> <tr> <th>Mulai</th> <th>Sampai</th> </tr> </thead> <tbody> <tr><td>1</td><td>Staff Seni dan Olahraga</td><td>Himpunan Mahasiswa Teknik Informatika</td><td>2022</td><td>2023</td></tr><tr><td>2</td><td>Staff Acara</td><td>Funcoustic HME X HMIF 2022</td><td>2022</td><td>2022</td> </tr> </tbody> <input type="text" id="title" name="title" > <button type="submit">Kirim</button> <br> </form> <p class="foot">Fadhilah Fauza Hamda</p>';
    
    const div = document.createElement('p'); 
    const teksDiv = document.createTextNode('Terimakasih!'); 
    div.appendChild(teksDiv);
    const cetak = document.getElementById('body'); 
  
    cetak.appendChild(div); 
  }